const axios = require('axios');

const API_URL = 'https://beecommercewatchstore-production.up.railway.app/api';

const luxuryWatches = [
  {
    name: 'Submariner Date',
    brand: 'Rolex',
    price: 14300,
    description: 'Iconic diving watch with date function, 300m water resistance, and ceramic bezel',
    images: ['https://images.unsplash.com/photo-1523170335258-f5ed11844a49'],
    category: 'Dive',
    movement: 'Automatic',
    caseMaterial: 'Stainless Steel',
    caseDiameter: 41,
    strapMaterial: 'Stainless Steel',
    waterResistance: 300,
    color: 'Black',
    stock: 5,
    isFeatured: true,
    isBestSeller: true,
  },
  {
    name: 'Daytona',
    brand: 'Rolex',
    price: 38000,
    description: 'Legendary racing chronograph, ceramic bezel, highly collectible',
    images: ['https://images.unsplash.com/photo-1622434641406-a158123450f9'],
    category: 'Chronograph',
    movement: 'Automatic',
    caseMaterial: 'Stainless Steel',
    caseDiameter: 40,
    strapMaterial: 'Stainless Steel',
    waterResistance: 100,
    color: 'White',
    stock: 2,
    isFeatured: true,
    isBestSeller: true,
  },
  {
    name: 'GMT-Master II',
    brand: 'Rolex',
    price: 18700,
    description: 'Dual timezone traveler watch, ceramic bezel, jubilee bracelet',
    images: ['https://images.unsplash.com/photo-1587836374775-5ac0c85d9e57'],
    category: 'GMT',
    movement: 'Automatic',
    caseMaterial: 'Stainless Steel',
    caseDiameter: 40,
    strapMaterial: 'Stainless Steel',
    waterResistance: 100,
    color: 'Black/Blue',
    stock: 3,
    isFeatured: true,
    isBestSeller: true,
  },
  {
    name: 'Datejust 41',
    brand: 'Rolex',
    price: 12800,
    description: 'Classic dress watch, fluted bezel, cyclops date magnifier',
    images: ['https://images.unsplash.com/photo-1594534475808-b18fc33b045e'],
    category: 'Dress',
    movement: 'Automatic',
    caseMaterial: 'Stainless Steel',
    caseDiameter: 41,
    strapMaterial: 'Jubilee',
    waterResistance: 100,
    color: 'Blue',
    stock: 8,
    isFeatured: false,
    isBestSeller: true,
  },
  {
    name: 'Sea-Dweller',
    brand: 'Rolex',
    price: 17900,
    description: 'Professional diving watch, 1220m water resistance, helium escape valve',
    images: ['https://images.unsplash.com/photo-1547996160-81dfa63595aa'],
    category: 'Dive',
    movement: 'Automatic',
    caseMaterial: 'Stainless Steel',
    caseDiameter: 43,
    strapMaterial: 'Oyster',
    waterResistance: 1220,
    color: 'Black',
    stock: 4,
    isFeatured: true,
    isBestSeller: false,
  },
  {
    name: 'Explorer II',
    brand: 'Rolex',
    price: 11250,
    description: 'Cave exploration watch, 24-hour bezel, fixed GMT hand',
    images: ['https://images.unsplash.com/photo-1509048191080-d2984bad6ae5'],
    category: 'Field',
    movement: 'Automatic',
    caseMaterial: 'Stainless Steel',
    caseDiameter: 42,
    strapMaterial: 'Oyster',
    waterResistance: 100,
    color: 'White',
    stock: 7,
    isFeatured: false,
    isBestSeller: true,
  },
  {
    name: 'Yacht-Master',
    brand: 'Rolex',
    price: 15650,
    description: 'Luxury sports watch for sailing, rotatable bezel, Oysterflex bracelet',
    images: ['https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3'],
    category: 'Dive',
    movement: 'Automatic',
    caseMaterial: 'Stainless Steel',
    caseDiameter: 40,
    strapMaterial: 'Oysterflex',
    waterResistance: 100,
    color: 'Rhodium',
    stock: 6,
    isFeatured: false,
    isBestSeller: false,
  },
  {
    name: 'Air-King',
    brand: 'Rolex',
    price: 7450,
    description: 'Aviation watch, bold black dial, excellent legibility',
    images: ['https://images.unsplash.com/photo-1524592094714-0f0654e20314'],
    category: 'Pilot',
    movement: 'Automatic',
    caseMaterial: 'Stainless Steel',
    caseDiameter: 40,
    strapMaterial: 'Oyster',
    waterResistance: 100,
    color: 'Black',
    stock: 12,
    isFeatured: false,
    isBestSeller: true,
  },
  {
    name: 'Oyster Perpetual 41',
    brand: 'Rolex',
    price: 6200,
    description: 'Entry-level Rolex, vibrant dial colors, versatile sports watch',
    images: ['https://images.unsplash.com/photo-1606390962981-e464eb6c5c39'],
    category: 'Dress',
    movement: 'Automatic',
    caseMaterial: 'Stainless Steel',
    caseDiameter: 41,
    strapMaterial: 'Oyster',
    waterResistance: 100,
    color: 'Turquoise',
    stock: 20,
    isFeatured: false,
    isBestSeller: true,
  },
  {
    name: 'Speedmaster Professional',
    brand: 'Omega',
    price: 6500,
    description: 'Moonwatch - First watch worn on the moon, manual chronograph',
    images: ['https://images.unsplash.com/photo-1614164185128-e4ec99c436d7'],
    category: 'Chronograph',
    movement: 'Manual',
    caseMaterial: 'Stainless Steel',
    caseDiameter: 42,
    strapMaterial: 'Leather',
    waterResistance: 50,
    color: 'Black',
    stock: 10,
    isFeatured: true,
    isBestSeller: true,
  },
  {
    name: 'Seamaster 300M',
    brand: 'Omega',
    price: 5400,
    description: 'James Bond watch, wave dial, helium escape valve',
    images: ['https://images.unsplash.com/photo-1606390962981-e464eb6c5c39'],
    category: 'Dive',
    movement: 'Automatic',
    caseMaterial: 'Stainless Steel',
    caseDiameter: 42,
    strapMaterial: 'Stainless Steel',
    waterResistance: 300,
    color: 'Blue',
    stock: 15,
    isFeatured: true,
    isBestSeller: true,
  },
  {
    name: 'Constellation',
    brand: 'Omega',
    price: 6800,
    description: 'Elegant dress watch, star emblem, Co-Axial escapement',
    images: ['https://images.unsplash.com/photo-1533139502658-0198f920d8e8'],
    category: 'Dress',
    movement: 'Automatic',
    caseMaterial: 'Stainless Steel',
    caseDiameter: 39,
    strapMaterial: 'Stainless Steel',
    waterResistance: 100,
    color: 'Silver',
    stock: 12,
    isFeatured: false,
    isBestSeller: true,
  },
  {
    name: 'Aqua Terra',
    brand: 'Omega',
    price: 5900,
    description: 'Versatile sports watch, teak dial pattern, Master Chronometer',
    images: ['https://images.unsplash.com/photo-1611148458170-9a16d9fdd1f6'],
    category: 'Dress',
    movement: 'Automatic',
    caseMaterial: 'Stainless Steel',
    caseDiameter: 41,
    strapMaterial: 'Stainless Steel',
    waterResistance: 150,
    color: 'Blue',
    stock: 9,
    isFeatured: false,
    isBestSeller: true,
  },
  {
    name: 'De Ville Prestige',
    brand: 'Omega',
    price: 4200,
    description: 'Classic dress watch, Roman numerals, elegant design',
    images: ['https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a'],
    category: 'Dress',
    movement: 'Automatic',
    caseMaterial: 'Stainless Steel',
    caseDiameter: 39,
    strapMaterial: 'Leather',
    waterResistance: 30,
    color: 'White',
    stock: 11,
    isFeatured: false,
    isBestSeller: false,
  },
  {
    name: 'Speedmaster Racing',
    brand: 'Omega',
    price: 5800,
    description: 'Racing chronograph, orange accents, automatic movement',
    images: ['https://images.unsplash.com/photo-1612817159949-195b6eb9e31a'],
    category: 'Chronograph',
    movement: 'Automatic',
    caseMaterial: 'Stainless Steel',
    caseDiameter: 44,
    strapMaterial: 'Stainless Steel',
    waterResistance: 100,
    color: 'Black',
    stock: 8,
    isFeatured: false,
    isBestSeller: false,
  },
  {
    name: 'Seamaster Planet Ocean',
    brand: 'Omega',
    price: 7200,
    description: 'Deep diving watch, 600m water resistant, ceramic bezel',
    images: ['https://images.unsplash.com/photo-1622434641406-a158123450f9'],
    category: 'Dive',
    movement: 'Automatic',
    caseMaterial: 'Stainless Steel',
    caseDiameter: 43,
    strapMaterial: 'Rubber',
    waterResistance: 600,
    color: 'Black',
    stock: 7,
    isFeatured: true,
    isBestSeller: false,
  },
  {
    name: 'Speedmaster Dark Side of the Moon',
    brand: 'Omega',
    price: 12900,
    description: 'All-black ceramic case, innovative design, Co-Axial movement',
    images: ['https://images.unsplash.com/photo-1625948515291-69613efd103f'],
    category: 'Chronograph',
    movement: 'Automatic',
    caseMaterial: 'Ceramic',
    caseDiameter: 44,
    strapMaterial: 'Leather',
    waterResistance: 50,
    color: 'Black',
    stock: 4,
    isFeatured: true,
    isBestSeller: false,
  },
  {
    name: 'Seamaster Diver 300M Chronograph',
    brand: 'Omega',
    price: 8200,
    description: 'Professional dive chronograph, ceramic bezel, Co-Axial movement',
    images: ['https://images.unsplash.com/photo-1622434641406-a158123450f9'],
    category: 'Chronograph',
    movement: 'Automatic',
    caseMaterial: 'Stainless Steel',
    caseDiameter: 44,
    strapMaterial: 'Rubber',
    waterResistance: 300,
    color: 'Black',
    stock: 9,
    isFeatured: false,
    isBestSeller: true,
  },
  {
    name: 'Nautilus',
    brand: 'Patek Philippe',
    price: 34890,
    description: 'Luxury sports watch with integrated bracelet, automatic movement',
    images: ['https://images.unsplash.com/photo-1587836374775-5ac0c85d9e57'],
    category: 'Dress',
    movement: 'Automatic',
    caseMaterial: 'Stainless Steel',
    caseDiameter: 40,
    strapMaterial: 'Stainless Steel',
    waterResistance: 120,
    color: 'Blue',
    stock: 2,
    isFeatured: true,
    isBestSeller: true,
  },
  {
    name: 'Aquanaut',
    brand: 'Patek Philippe',
    price: 28400,
    description: 'Modern sports watch, tropical composite strap, water resistant',
    images: ['https://images.unsplash.com/photo-1594534475808-b18fc33b045e'],
    category: 'Dive',
    movement: 'Automatic',
    caseMaterial: 'Stainless Steel',
    caseDiameter: 40,
    strapMaterial: 'Composite',
    waterResistance: 120,
    color: 'Black',
    stock: 3,
    isFeatured: true,
    isBestSeller: true,
  },
  {
    name: 'Calatrava',
    brand: 'Patek Philippe',
    price: 22500,
    description: 'Classic dress watch, Bauhaus design, hand-wound movement',
    images: ['https://images.unsplash.com/photo-1533139502658-0198f920d8e8'],
    category: 'Dress',
    movement: 'Manual',
    caseMaterial: 'White Gold',
    caseDiameter: 39,
    strapMaterial: 'Leather',
    waterResistance: 30,
    color: 'White',
    stock: 4,
    isFeatured: true,
    isBestSeller: false,
  },
  {
    name: 'Complications Annual Calendar',
    brand: 'Patek Philippe',
    price: 42800,
    description: 'Annual calendar complication, moon phase, elegant design',
    images: ['https://images.unsplash.com/photo-1611148458170-9a16d9fdd1f6'],
    category: 'Dress',
    movement: 'Automatic',
    caseMaterial: 'Rose Gold',
    caseDiameter: 40,
    strapMaterial: 'Leather',
    waterResistance: 30,
    color: 'Champagne',
    stock: 2,
    isFeatured: true,
    isBestSeller: false,
  },
  {
    name: 'Grand Complications Perpetual Calendar',
    brand: 'Patek Philippe',
    price: 98000,
    description: 'Perpetual calendar, moon phase, minute repeater, masterpiece',
    images: ['https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a'],
    category: 'Dress',
    movement: 'Manual',
    caseMaterial: 'Platinum',
    caseDiameter: 41,
    strapMaterial: 'Alligator',
    waterResistance: 30,
    color: 'Blue',
    stock: 1,
    isFeatured: true,
    isBestSeller: false,
  },
  {
    name: 'Twenty-4 Automatic',
    brand: 'Patek Philippe',
    price: 18900,
    description: 'Ladies automatic watch, diamond bezel, elegant bracelet',
    images: ['https://images.unsplash.com/photo-1614164185128-e4ec99c436d7'],
    category: 'Dress',
    movement: 'Automatic',
    caseMaterial: 'Stainless Steel',
    caseDiameter: 36,
    strapMaterial: 'Stainless Steel',
    waterResistance: 30,
    color: 'Silver',
    stock: 5,
    isFeatured: false,
    isBestSeller: true,
  },
  {
    name: 'Gondolo',
    brand: 'Patek Philippe',
    price: 26500,
    description: 'Art Deco inspired, tonneau case, manual winding',
    images: ['https://images.unsplash.com/photo-1606390962981-e464eb6c5c39'],
    category: 'Dress',
    movement: 'Manual',
    caseMaterial: 'Rose Gold',
    caseDiameter: 34,
    strapMaterial: 'Alligator',
    waterResistance: 30,
    color: 'White',
    stock: 3,
    isFeatured: false,
    isBestSeller: false,
  },
  {
    name: 'World Time',
    brand: 'Patek Philippe',
    price: 54200,
    description: 'World time complication, 24 time zones, cloisonné dial',
    images: ['https://images.unsplash.com/photo-1612817159949-195b6eb9e31a'],
    category: 'Dress',
    movement: 'Automatic',
    caseMaterial: 'White Gold',
    caseDiameter: 39,
    strapMaterial: 'Alligator',
    waterResistance: 30,
    color: 'Blue',
    stock: 2,
    isFeatured: true,
    isBestSeller: false,
  },
  {
    name: 'Black Bay Fifty-Eight',
    brand: 'Tudor',
    price: 3975,
    description: 'Vintage-inspired dive watch, 200m water resistant, affordable luxury',
    images: ['https://images.unsplash.com/photo-1622434641406-a158123450f9'],
    category: 'Dive',
    movement: 'Automatic',
    caseMaterial: 'Stainless Steel',
    caseDiameter: 39,
    strapMaterial: 'Fabric',
    waterResistance: 200,
    color: 'Black',
    stock: 18,
    isFeatured: true,
    isBestSeller: true,
  },
  {
    name: 'Pelagos FXD',
    brand: 'Tudor',
    price: 4200,
    description: 'Military dive watch, fixed strap bars, titanium case',
    images: ['https://images.unsplash.com/photo-1625948515291-69613efd103f'],
    category: 'Dive',
    movement: 'Automatic',
    caseMaterial: 'Titanium',
    caseDiameter: 42,
    strapMaterial: 'Fabric',
    waterResistance: 200,
    color: 'Black',
    stock: 12,
    isFeatured: false,
    isBestSeller: true,
  },
  {
    name: 'Black Bay GMT',
    brand: 'Tudor',
    price: 4500,
    description: 'GMT function, Pepsi bezel, versatile travel watch',
    images: ['https://images.unsplash.com/photo-1614164185816-0e043ea08013'],
    category: 'GMT',
    movement: 'Automatic',
    caseMaterial: 'Stainless Steel',
    caseDiameter: 41,
    strapMaterial: 'Stainless Steel',
    waterResistance: 200,
    color: 'Red/Blue',
    stock: 10,
    isFeatured: true,
    isBestSeller: true,
  },
  {
    name: 'Black Bay Chrono',
    brand: 'Tudor',
    price: 5800,
    description: 'Chronograph dive watch, column-wheel movement, vintage design',
    images: ['https://images.unsplash.com/photo-1607513234392-fab5ed87e611'],
    category: 'Chronograph',
    movement: 'Automatic',
    caseMaterial: 'Stainless Steel',
    caseDiameter: 41,
    strapMaterial: 'Stainless Steel',
    waterResistance: 200,
    color: 'Black',
    stock: 8,
    isFeatured: false,
    isBestSeller: false,
  },
  {
    name: 'Pelagos',
    brand: 'Tudor',
    price: 4950,
    description: 'Professional dive watch, 500m water resistant, titanium construction',
    images: ['https://images.unsplash.com/photo-1618481187757-5d27c7dc3071'],
    category: 'Dive',
    movement: 'Automatic',
    caseMaterial: 'Titanium',
    caseDiameter: 42,
    strapMaterial: 'Titanium',
    waterResistance: 500,
    color: 'Blue',
    stock: 11,
    isFeatured: true,
    isBestSeller: false,
  },
  {
    name: 'Ranger',
    brand: 'Tudor',
    price: 3100,
    description: 'Field watch, 39mm case, explorer heritage',
    images: ['https://images.unsplash.com/photo-1639006570490-79c0c53f1080'],
    category: 'Field',
    movement: 'Automatic',
    caseMaterial: 'Stainless Steel',
    caseDiameter: 39,
    strapMaterial: 'Fabric',
    waterResistance: 100,
    color: 'Black',
    stock: 15,
    isFeatured: false,
    isBestSeller: true,
  },
  {
    name: 'Royal',
    brand: 'Tudor',
    price: 2650,
    description: 'Classic dress watch, date function, affordable luxury',
    images: ['https://images.unsplash.com/photo-1611148458170-9a16d9fdd1f6'],
    category: 'Dress',
    movement: 'Automatic',
    caseMaterial: 'Stainless Steel',
    caseDiameter: 41,
    strapMaterial: 'Stainless Steel',
    waterResistance: 100,
    color: 'Silver',
    stock: 20,
    isFeatured: false,
    isBestSeller: true,
  },
  {
    name: 'Black Bay Ceramic',
    brand: 'Tudor',
    price: 5200,
    description: 'All-black ceramic case, Master Chronometer, limited edition',
    images: ['https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a'],
    category: 'Dive',
    movement: 'Automatic',
    caseMaterial: 'Ceramic',
    caseDiameter: 41,
    strapMaterial: 'Fabric',
    waterResistance: 200,
    color: 'Black',
    stock: 5,
    isFeatured: true,
    isBestSeller: false,
  },
  {
    name: 'Santos Medium',
    brand: 'Cartier',
    price: 7350,
    description: 'Square case with visible screws, elegant dress watch',
    images: ['https://images.unsplash.com/photo-1533139502658-0198f920d8e8'],
    category: 'Dress',
    movement: 'Automatic',
    caseMaterial: 'Stainless Steel',
    caseDiameter: 39,
    strapMaterial: 'Leather',
    waterResistance: 100,
    color: 'White',
    stock: 14,
    isFeatured: true,
    isBestSeller: true,
  },
  {
    name: 'Tank Must',
    brand: 'Cartier',
    price: 3500,
    description: 'Iconic rectangular case, Roman numerals, Art Deco design',
    images: ['https://images.unsplash.com/photo-1594534475808-b18fc33b045e'],
    category: 'Dress',
    movement: 'Quartz',
    caseMaterial: 'Stainless Steel',
    caseDiameter: 33,
    strapMaterial: 'Leather',
    waterResistance: 30,
    color: 'Silver',
    stock: 25,
    isFeatured: true,
    isBestSeller: true,
  },
  {
    name: 'Ballon Bleu',
    brand: 'Cartier',
    price: 6900,
    description: 'Round case with blue crown, elegant proportions',
    images: ['https://images.unsplash.com/photo-1587836374775-5ac0c85d9e57'],
    category: 'Dress',
    movement: 'Automatic',
    caseMaterial: 'Stainless Steel',
    caseDiameter: 42,
    strapMaterial: 'Leather',
    waterResistance: 30,
    color: 'Silver',
    stock: 12,
    isFeatured: false,
    isBestSeller: true,
  },
  {
    name: 'Drive de Cartier',
    brand: 'Cartier',
    price: 7800,
    description: 'Cushion-shaped case, automatic movement, refined design',
    images: ['https://images.unsplash.com/photo-1606390962981-e464eb6c5c39'],
    category: 'Dress',
    movement: 'Automatic',
    caseMaterial: 'Stainless Steel',
    caseDiameter: 40,
    strapMaterial: 'Alligator',
    waterResistance: 30,
    color: 'White',
    stock: 9,
    isFeatured: false,
    isBestSeller: false,
  },
  {
    name: 'Panthère',
    brand: 'Cartier',
    price: 5200,
    description: 'Ladies luxury watch, integrated bracelet, iconic design',
    images: ['https://images.unsplash.com/photo-1614164185128-e4ec99c436d7'],
    category: 'Dress',
    movement: 'Quartz',
    caseMaterial: 'Stainless Steel',
    caseDiameter: 27,
    strapMaterial: 'Stainless Steel',
    waterResistance: 30,
    color: 'Silver',
    stock: 16,
    isFeatured: false,
    isBestSeller: true,
  },
  {
    name: 'Ronde de Cartier',
    brand: 'Cartier',
    price: 4800,
    description: 'Classic round case, Roman numerals, guilloche dial',
    images: ['https://images.unsplash.com/photo-1611148458170-9a16d9fdd1f6'],
    category: 'Dress',
    movement: 'Automatic',
    caseMaterial: 'Stainless Steel',
    caseDiameter: 40,
    strapMaterial: 'Alligator',
    waterResistance: 30,
    color: 'Silver',
    stock: 11,
    isFeatured: false,
    isBestSeller: false,
  },
  {
    name: 'Santos-Dumont',
    brand: 'Cartier',
    price: 5500,
    description: 'Ultra-thin dress watch, manual winding, vintage inspired',
    images: ['https://images.unsplash.com/photo-1612817159949-195b6eb9e31a'],
    category: 'Dress',
    movement: 'Manual',
    caseMaterial: 'Stainless Steel',
    caseDiameter: 38,
    strapMaterial: 'Alligator',
    waterResistance: 30,
    color: 'Champagne',
    stock: 8,
    isFeatured: true,
    isBestSeller: false,
  },
  {
    name: 'Tortue',
    brand: 'Cartier',
    price: 12800,
    description: 'Tonneau-shaped case, manual movement, rare collectible',
    images: ['https://images.unsplash.com/photo-1625948515291-69613efd103f'],
    category: 'Dress',
    movement: 'Manual',
    caseMaterial: 'Rose Gold',
    caseDiameter: 36,
    strapMaterial: 'Alligator',
    waterResistance: 30,
    color: 'Silver',
    stock: 3,
    isFeatured: false,
    isBestSeller: false,
  },
  {
    name: 'Carrera Calibre 16',
    brand: 'Tag Heuer',
    price: 4850,
    description: 'Racing chronograph with tachymeter, sporty design',
    images: ['https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3'],
    category: 'Chronograph',
    movement: 'Automatic',
    caseMaterial: 'Stainless Steel',
    caseDiameter: 43,
    strapMaterial: 'Leather',
    waterResistance: 100,
    color: 'Black',
    stock: 16,
    isFeatured: true,
    isBestSeller: true,
  },
  {
    name: 'Monaco',
    brand: 'Tag Heuer',
    price: 6950,
    description: 'Iconic square case, Steve McQueen watch, automatic chronograph',
    images: ['https://images.unsplash.com/photo-1524592094714-0f0654e20314'],
    category: 'Chronograph',
    movement: 'Automatic',
    caseMaterial: 'Stainless Steel',
    caseDiameter: 39,
    strapMaterial: 'Leather',
    waterResistance: 100,
    color: 'Blue',
    stock: 10,
    isFeatured: true,
    isBestSeller: true,
  },
  {
    name: 'Aquaracer Professional 300',
    brand: 'Tag Heuer',
    price: 3200,
    description: 'Professional dive watch, unidirectional bezel, 300m water resistant',
    images: ['https://images.unsplash.com/photo-1509048191080-d2984bad6ae5'],
    category: 'Dive',
    movement: 'Automatic',
    caseMaterial: 'Stainless Steel',
    caseDiameter: 43,
    strapMaterial: 'Stainless Steel',
    waterResistance: 300,
    color: 'Blue',
    stock: 22,
    isFeatured: false,
    isBestSeller: true,
  },
  {
    name: 'Autavia',
    brand: 'Tag Heuer',
    price: 5200,
    description: 'Vintage racing chronograph, bi-directional bezel, heritage design',
    images: ['https://images.unsplash.com/photo-1547996160-81dfa63595aa'],
    category: 'Chronograph',
    movement: 'Automatic',
    caseMaterial: 'Stainless Steel',
    caseDiameter: 42,
    strapMaterial: 'Leather',
    waterResistance: 100,
    color: 'Black',
    stock: 12,
    isFeatured: false,
    isBestSeller: false,
  },
  {
    name: 'Formula 1',
    brand: 'Tag Heuer',
    price: 1850,
    description: 'Sporty quartz chronograph, excellent value, racing inspired',
    images: ['https://images.unsplash.com/photo-1614164185816-0e043ea08013'],
    category: 'Chronograph',
    movement: 'Quartz',
    caseMaterial: 'Stainless Steel',
    caseDiameter: 43,
    strapMaterial: 'Stainless Steel',
    waterResistance: 200,
    color: 'Red',
    stock: 30,
    isFeatured: false,
    isBestSeller: true,
  },
  {
    name: 'Link',
    brand: 'Tag Heuer',
    price: 2750,
    description: 'Sporty bracelet watch, S-shaped links, versatile design',
    images: ['https://images.unsplash.com/photo-1607513234392-fab5ed87e611'],
    category: 'Dress',
    movement: 'Automatic',
    caseMaterial: 'Stainless Steel',
    caseDiameter: 41,
    strapMaterial: 'Stainless Steel',
    waterResistance: 100,
    color: 'Blue',
    stock: 18,
    isFeatured: false,
    isBestSeller: true,
  },
  {
    name: 'Carrera Sport Chronograph',
    brand: 'Tag Heuer',
    price: 5500,
    description: 'Modern sports chronograph, ceramic bezel, bold design',
    images: ['https://images.unsplash.com/photo-1618481187757-5d27c7dc3071'],
    category: 'Chronograph',
    movement: 'Automatic',
    caseMaterial: 'Stainless Steel',
    caseDiameter: 44,
    strapMaterial: 'Rubber',
    waterResistance: 100,
    color: 'Black',
    stock: 14,
    isFeatured: true,
    isBestSeller: false,
  },
  {
    name: 'Aquaracer GMT',
    brand: 'Tag Heuer',
    price: 4100,
    description: 'Dive watch with GMT function, 300m water resistant, rotating bezel',
    images: ['https://images.unsplash.com/photo-1639006570490-79c0c53f1080'],
    category: 'GMT',
    movement: 'Automatic',
    caseMaterial: 'Stainless Steel',
    caseDiameter: 43,
    strapMaterial: 'Stainless Steel',
    waterResistance: 300,
    color: 'Blue/Red',
    stock: 11,
    isFeatured: false,
    isBestSeller: false,
  },
];

async function seedProducts() {
  console.log('🌱 Starting to seed 50 luxury watch products...\n');
  console.log('📋 Brands: Rolex, Omega, Patek Philippe, Tudor, Cartier, Tag Heuer\n');
  console.log('⚠️  Important: You must be logged in as ADMIN to run this script!\n');
  
  const token = process.env.AUTH_TOKEN || '';
  if (!token) {
    console.error('❌ Error: AUTH_TOKEN environment variable not set!');
    console.error('   Please login as admin first and set AUTH_TOKEN=your-token\n');
    process.exit(1);
  }
  
  let successCount = 0;
  let errorCount = 0;

  for (let i = 0; i < luxuryWatches.length; i++) {
    const watch = luxuryWatches[i];
    try {
      await axios.post(`${API_URL}/watches`, watch, {
        headers: {
          'Authorization': `Bearer ${token}`,
          'Content-Type': 'application/json'
        }
      });
      successCount++;
      console.log(`✅ [${i + 1}/50] Created: ${watch.brand} ${watch.name}`);
    } catch (error) {
      errorCount++;
      console.error(`❌ [${i + 1}/50] Failed: ${watch.brand} ${watch.name}`);
      if (error.response) {
        console.error(`   Error: ${error.response.status} - ${error.response.data.message || error.response.statusText}`);
      } else {
        console.error(`   Error: ${error.message}`);
      }
    }
  }

  console.log(`\n📊 Seed Summary:`);
  console.log(`   ✅ Success: ${successCount}`);
  console.log(`   ❌ Failed: ${errorCount}`);
  console.log(`   📦 Total: ${luxuryWatches.length}`);
  
  console.log(`\n🏷️  Brands Distribution:`);
  const brandCounts = {};
  luxuryWatches.forEach(watch => {
    brandCounts[watch.brand] = (brandCounts[watch.brand] || 0) + 1;
  });
  
  Object.entries(brandCounts).forEach(([brand, count]) => {
    console.log(`   ${brand}: ${count} products`);
  });
}

seedProducts()
  .then(() => {
    console.log('\n✨ Seeding completed!');
    process.exit(0);
  })
  .catch((error) => {
    console.error('\n💥 Seeding failed:', error.message);
    process.exit(1);
  });
