import { productsApi } from '../src/lib/api';

const luxuryWatches = [
  {
    name: 'Rolex Submariner Date',
    brand: 'Rolex',
    price: 14300,
    description: 'Iconic diving watch with date function, 300m water resistance, and ceramic bezel',
    images: ['https://images.unsplash.com/photo-1523170335258-f5ed11844a49'],
    category: 'Dive',
    movement: 'Automatic',
    caseMaterial: 'Stainless Steel',
    caseDiameter: 41,
    strapMaterial: 'Stainless Steel',
    waterResistance: 300,
    color: 'Black',
    stock: 5,
    isFeatured: true,
    isBestSeller: true,
  },
  {
    name: 'Omega Speedmaster Professional',
    brand: 'Omega',
    price: 6500,
    description: 'Moonwatch - First watch worn on the moon, manual chronograph',
    images: ['https://images.unsplash.com/photo-1547996160-81dfa63595aa'],
    category: 'Chronograph',
    movement: 'Manual',
    caseMaterial: 'Stainless Steel',
    caseDiameter: 42,
    strapMaterial: 'Leather',
    waterResistance: 50,
    color: 'Black',
    stock: 8,
    isFeatured: true,
    isBestSeller: true,
  },
  {
    name: 'Patek Philippe Nautilus',
    brand: 'Patek Philippe',
    price: 34890,
    description: 'Luxury sports watch with integrated bracelet, automatic movement',
    images: ['https://images.unsplash.com/photo-1587836374775-5ac0c85d9e57'],
    category: 'Dress',
    movement: 'Automatic',
    caseMaterial: 'Stainless Steel',
    caseDiameter: 40,
    strapMaterial: 'Stainless Steel',
    waterResistance: 120,
    color: 'Blue',
    stock: 2,
    isFeatured: true,
    isBestSeller: false,
  },
  {
    name: 'Audemars Piguet Royal Oak',
    brand: 'Audemars Piguet',
    price: 29800,
    description: 'Iconic octagonal bezel, tapisserie dial, luxury sports watch',
    images: ['https://images.unsplash.com/photo-1509048191080-d2984bad6ae5'],
    category: 'Dress',
    movement: 'Automatic',
    caseMaterial: 'Stainless Steel',
    caseDiameter: 41,
    strapMaterial: 'Stainless Steel',
    waterResistance: 50,
    color: 'Blue',
    stock: 3,
    isFeatured: true,
    isBestSeller: true,
  },
  {
    name: 'TAG Heuer Carrera Calibre 16',
    brand: 'TAG Heuer',
    price: 4850,
    description: 'Racing chronograph with tachymeter, sporty design',
    images: ['https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3'],
    category: 'Chronograph',
    movement: 'Automatic',
    caseMaterial: 'Stainless Steel',
    caseDiameter: 43,
    strapMaterial: 'Leather',
    waterResistance: 100,
    color: 'Black',
    stock: 12,
    isFeatured: false,
    isBestSeller: true,
  },
  {
    name: 'IWC Pilot\'s Watch Mark XX',
    brand: 'IWC',
    price: 5400,
    description: 'Classic pilot watch with excellent readability and precision',
    images: ['https://images.unsplash.com/photo-1524592094714-0f0654e20314'],
    category: 'Pilot',
    movement: 'Automatic',
    caseMaterial: 'Stainless Steel',
    caseDiameter: 40,
    strapMaterial: 'Leather',
    waterResistance: 100,
    color: 'Black',
    stock: 7,
    isFeatured: false,
    isBestSeller: false,
  },
  {
    name: 'Breitling Navitimer B01',
    brand: 'Breitling',
    price: 8600,
    description: 'Aviation chronograph with slide rule bezel for calculations',
    images: ['https://images.unsplash.com/photo-1614164185128-e4ec99c436d7'],
    category: 'Chronograph',
    movement: 'Automatic',
    caseMaterial: 'Stainless Steel',
    caseDiameter: 43,
    strapMaterial: 'Stainless Steel',
    waterResistance: 30,
    color: 'Blue',
    stock: 6,
    isFeatured: true,
    isBestSeller: false,
  },
  {
    name: 'Cartier Santos Medium',
    brand: 'Cartier',
    price: 7350,
    description: 'Square case with visible screws, elegant dress watch',
    images: ['https://images.unsplash.com/photo-1533139502658-0198f920d8e8'],
    category: 'Dress',
    movement: 'Automatic',
    caseMaterial: 'Stainless Steel',
    caseDiameter: 39,
    strapMaterial: 'Leather',
    waterResistance: 100,
    color: 'White',
    stock: 9,
    isFeatured: false,
    isBestSeller: true,
  },
  {
    name: 'Jaeger-LeCoultre Reverso Classic',
    brand: 'Jaeger-LeCoultre',
    price: 6200,
    description: 'Iconic reversible case, Art Deco design, manual winding',
    images: ['https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a'],
    category: 'Dress',
    movement: 'Manual',
    caseMaterial: 'Stainless Steel',
    caseDiameter: 38,
    strapMaterial: 'Leather',
    waterResistance: 30,
    color: 'Silver',
    stock: 4,
    isFeatured: true,
    isBestSeller: false,
  },
  {
    name: 'Zenith Chronomaster Sport',
    brand: 'Zenith',
    price: 9900,
    description: 'High-frequency chronograph, El Primero movement, 1/10 second precision',
    images: ['https://images.unsplash.com/photo-1611148458170-9a16d9fdd1f6'],
    category: 'Chronograph',
    movement: 'Automatic',
    caseMaterial: 'Stainless Steel',
    caseDiameter: 41,
    strapMaterial: 'Stainless Steel',
    waterResistance: 100,
    color: 'Black',
    stock: 5,
    isFeatured: false,
    isBestSeller: true,
  },
  {
    name: 'Panerai Luminor Marina',
    brand: 'Panerai',
    price: 7800,
    description: 'Italian design, crown protection system, luminous markers',
    images: ['https://images.unsplash.com/photo-1612817159949-195b6eb9e31a'],
    category: 'Dive',
    movement: 'Automatic',
    caseMaterial: 'Stainless Steel',
    caseDiameter: 44,
    strapMaterial: 'Leather',
    waterResistance: 300,
    color: 'Black',
    stock: 6,
    isFeatured: false,
    isBestSeller: false,
  },
  {
    name: 'Tudor Black Bay Fifty-Eight',
    brand: 'Tudor',
    price: 3975,
    description: 'Vintage-inspired dive watch, 200m water resistant, affordable luxury',
    images: ['https://images.unsplash.com/photo-1622434641406-a158123450f9'],
    category: 'Dive',
    movement: 'Automatic',
    caseMaterial: 'Stainless Steel',
    caseDiameter: 39,
    strapMaterial: 'Fabric',
    waterResistance: 200,
    color: 'Black',
    stock: 15,
    isFeatured: true,
    isBestSeller: true,
  },
  {
    name: 'Vacheron Constantin Overseas',
    brand: 'Vacheron Constantin',
    price: 24500,
    description: 'Luxury sports watch with interchangeable strap system',
    images: ['https://images.unsplash.com/photo-1594534475808-b18fc33b045e'],
    category: 'Dress',
    movement: 'Automatic',
    caseMaterial: 'Stainless Steel',
    caseDiameter: 41,
    strapMaterial: 'Stainless Steel',
    waterResistance: 150,
    color: 'Blue',
    stock: 3,
    isFeatured: true,
    isBestSeller: false,
  },
  {
    name: 'Grand Seiko Snowflake',
    brand: 'Grand Seiko',
    price: 6200,
    description: 'Spring Drive movement, unique textured dial, Japanese craftsmanship',
    images: ['https://images.unsplash.com/photo-1617625802912-cdf23d9a6e18'],
    category: 'Dress',
    movement: 'Spring Drive',
    caseMaterial: 'Titanium',
    caseDiameter: 41,
    strapMaterial: 'Leather',
    waterResistance: 100,
    color: 'White',
    stock: 8,
    isFeatured: true,
    isBestSeller: true,
  },
  {
    name: 'Hublot Big Bang Unico',
    brand: 'Hublot',
    price: 18900,
    description: 'Bold design, in-house chronograph movement, sapphire crystal',
    images: ['https://images.unsplash.com/photo-1625948515291-69613efd103f'],
    category: 'Chronograph',
    movement: 'Automatic',
    caseMaterial: 'Ceramic',
    caseDiameter: 45,
    strapMaterial: 'Rubber',
    waterResistance: 100,
    color: 'Black',
    stock: 4,
    isFeatured: false,
    isBestSeller: false,
  },
  {
    name: 'Longines Master Collection',
    brand: 'Longines',
    price: 2650,
    description: 'Classic dress watch, moon phase complication, excellent value',
    images: ['https://images.unsplash.com/photo-1606390962981-e464eb6c5c39'],
    category: 'Dress',
    movement: 'Automatic',
    caseMaterial: 'Stainless Steel',
    caseDiameter: 40,
    strapMaterial: 'Leather',
    waterResistance: 30,
    color: 'White',
    stock: 18,
    isFeatured: false,
    isBestSeller: true,
  },
  {
    name: 'Bell & Ross BR 03-92 Diver',
    brand: 'Bell & Ross',
    price: 4200,
    description: 'Square dive watch, aviation-inspired design, 300m water resistant',
    images: ['https://images.unsplash.com/photo-1639006570490-79c0c53f1080'],
    category: 'Dive',
    movement: 'Automatic',
    caseMaterial: 'Ceramic',
    caseDiameter: 42,
    strapMaterial: 'Rubber',
    waterResistance: 300,
    color: 'Black',
    stock: 7,
    isFeatured: false,
    isBestSeller: false,
  },
  {
    name: 'Chopard Mille Miglia GTS',
    brand: 'Chopard',
    price: 5800,
    description: 'Racing chronograph, vintage-inspired design, limited edition',
    images: ['https://images.unsplash.com/photo-1607513234392-fab5ed87e611'],
    category: 'Chronograph',
    movement: 'Automatic',
    caseMaterial: 'Stainless Steel',
    caseDiameter: 44,
    strapMaterial: 'Leather',
    waterResistance: 100,
    color: 'Black',
    stock: 5,
    isFeatured: false,
    isBestSeller: false,
  },
  {
    name: 'Oris Aquis Date',
    brand: 'Oris',
    price: 2100,
    description: 'Professional dive watch, 300m water resistant, affordable Swiss made',
    images: ['https://images.unsplash.com/photo-1618481187757-5d27c7dc3071'],
    category: 'Dive',
    movement: 'Automatic',
    caseMaterial: 'Stainless Steel',
    caseDiameter: 43,
    strapMaterial: 'Rubber',
    waterResistance: 300,
    color: 'Blue',
    stock: 20,
    isFeatured: false,
    isBestSeller: true,
  },
  {
    name: 'Montblanc 1858 Automatic',
    brand: 'Montblanc',
    price: 3900,
    description: 'Mountain exploration watch, vintage aesthetics, bronze case',
    images: ['https://images.unsplash.com/photo-1614164185816-0e043ea08013'],
    category: 'Field',
    movement: 'Automatic',
    caseMaterial: 'Bronze',
    caseDiameter: 40,
    strapMaterial: 'Leather',
    waterResistance: 100,
    color: 'Green',
    stock: 9,
    isFeatured: true,
    isBestSeller: false,
  },
  {
    name: 'Rolex Daytona',
    brand: 'Rolex',
    price: 38000,
    description: 'Legendary racing chronograph, ceramic bezel, highly collectible',
    images: ['https://images.unsplash.com/photo-1622434641406-a158123450f9'],
    category: 'Chronograph',
    movement: 'Automatic',
    caseMaterial: 'Stainless Steel',
    caseDiameter: 40,
    strapMaterial: 'Stainless Steel',
    waterResistance: 100,
    color: 'White',
    stock: 1,
    isFeatured: true,
    isBestSeller: true,
  },
  {
    name: 'Omega Seamaster 300M',
    brand: 'Omega',
    price: 5400,
    description: 'James Bond watch, wave dial, helium escape valve',
    images: ['https://images.unsplash.com/photo-1606390962981-e464eb6c5c39'],
    category: 'Dive',
    movement: 'Automatic',
    caseMaterial: 'Stainless Steel',
    caseDiameter: 42,
    strapMaterial: 'Stainless Steel',
    waterResistance: 300,
    color: 'Blue',
    stock: 11,
    isFeatured: true,
    isBestSeller: true,
  },
  {
    name: 'Breguet Classique',
    brand: 'Breguet',
    price: 19800,
    description: 'Traditional watchmaking, guilloché dial, hand-engraved',
    images: ['https://images.unsplash.com/photo-1594534475808-b18fc33b045e'],
    category: 'Dress',
    movement: 'Manual',
    caseMaterial: 'White Gold',
    caseDiameter: 38,
    strapMaterial: 'Leather',
    waterResistance: 30,
    color: 'Silver',
    stock: 2,
    isFeatured: true,
    isBestSeller: false,
  },
  {
    name: 'Seiko Prospex SPB143',
    brand: 'Seiko',
    price: 1050,
    description: 'Modern re-interpretation of 62MAS, affordable dive watch',
    images: ['https://images.unsplash.com/photo-1611148458170-9a16d9fdd1f6'],
    category: 'Dive',
    movement: 'Automatic',
    caseMaterial: 'Stainless Steel',
    caseDiameter: 40,
    strapMaterial: 'Stainless Steel',
    waterResistance: 200,
    color: 'Black',
    stock: 25,
    isFeatured: false,
    isBestSeller: true,
  },
  {
    name: 'Hamilton Khaki Field Mechanical',
    brand: 'Hamilton',
    price: 595,
    description: 'Military-inspired field watch, manual wind, excellent value',
    images: ['https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a'],
    category: 'Field',
    movement: 'Manual',
    caseMaterial: 'Stainless Steel',
    caseDiameter: 38,
    strapMaterial: 'Leather',
    waterResistance: 50,
    color: 'Black',
    stock: 30,
    isFeatured: false,
    isBestSeller: true,
  },
  {
    name: 'A. Lange & Söhne Lange 1',
    brand: 'A. Lange & Söhne',
    price: 38500,
    description: 'German haute horlogerie, asymmetric dial, outsize date',
    images: ['https://images.unsplash.com/photo-1587836374775-5ac0c85d9e57'],
    category: 'Dress',
    movement: 'Manual',
    caseMaterial: 'White Gold',
    caseDiameter: 38,
    strapMaterial: 'Leather',
    waterResistance: 30,
    color: 'Silver',
    stock: 1,
    isFeatured: true,
    isBestSeller: false,
  },
  {
    name: 'Blancpain Fifty Fathoms',
    brand: 'Blancpain',
    price: 15300,
    description: 'First modern dive watch, unidirectional bezel, 300m',
    images: ['https://images.unsplash.com/photo-1533139502658-0198f920d8e8'],
    category: 'Dive',
    movement: 'Automatic',
    caseMaterial: 'Stainless Steel',
    caseDiameter: 45,
    strapMaterial: 'Canvas',
    waterResistance: 300,
    color: 'Black',
    stock: 4,
    isFeatured: true,
    isBestSeller: false,
  },
  {
    name: 'Tissot PRX Powermatic 80',
    brand: 'Tissot',
    price: 695,
    description: 'Retro integrated bracelet, 80-hour power reserve, best value',
    images: ['https://images.unsplash.com/photo-1622434641406-a158123450f9'],
    category: 'Dress',
    movement: 'Automatic',
    caseMaterial: 'Stainless Steel',
    caseDiameter: 40,
    strapMaterial: 'Stainless Steel',
    waterResistance: 100,
    color: 'Blue',
    stock: 35,
    isFeatured: false,
    isBestSeller: true,
  },
  {
    name: 'Girard-Perregaux Laureato',
    brand: 'Girard-Perregaux',
    price: 12900,
    description: 'Luxury sports watch, octagonal bezel, integrated bracelet',
    images: ['https://images.unsplash.com/photo-1614164185128-e4ec99c436d7'],
    category: 'Dress',
    movement: 'Automatic',
    caseMaterial: 'Stainless Steel',
    caseDiameter: 42,
    strapMaterial: 'Stainless Steel',
    waterResistance: 100,
    color: 'Blue',
    stock: 5,
    isFeatured: false,
    isBestSeller: false,
  },
  {
    name: 'Glashütte Original SeaQ',
    brand: 'Glashütte Original',
    price: 9800,
    description: 'German dive watch, panorama date, ceramic bezel',
    images: ['https://images.unsplash.com/photo-1524592094714-0f0654e20314'],
    category: 'Dive',
    movement: 'Automatic',
    caseMaterial: 'Stainless Steel',
    caseDiameter: 43,
    strapMaterial: 'Rubber',
    waterResistance: 300,
    color: 'Green',
    stock: 6,
    isFeatured: false,
    isBestSeller: false,
  },
  {
    name: 'Maurice Lacroix Aikon Automatic',
    brand: 'Maurice Lacroix',
    price: 1950,
    description: 'Six-arm star emblem, integrated bracelet, Swiss made',
    images: ['https://images.unsplash.com/photo-1509048191080-d2984bad6ae5'],
    category: 'Dress',
    movement: 'Automatic',
    caseMaterial: 'Stainless Steel',
    caseDiameter: 42,
    strapMaterial: 'Stainless Steel',
    waterResistance: 200,
    color: 'Blue',
    stock: 14,
    isFeatured: false,
    isBestSeller: false,
  },
  {
    name: 'Nomos Tangente',
    brand: 'Nomos Glashütte',
    price: 2200,
    description: 'Bauhaus design, in-house movement, minimalist elegance',
    images: ['https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3'],
    category: 'Dress',
    movement: 'Manual',
    caseMaterial: 'Stainless Steel',
    caseDiameter: 38,
    strapMaterial: 'Leather',
    waterResistance: 30,
    color: 'White',
    stock: 12,
    isFeatured: false,
    isBestSeller: true,
  },
  {
    name: 'Ulysse Nardin Diver',
    brand: 'Ulysse Nardin',
    price: 9200,
    description: 'Professional dive watch, concave bezel, silicon technology',
    images: ['https://images.unsplash.com/photo-1547996160-81dfa63595aa'],
    category: 'Dive',
    movement: 'Automatic',
    caseMaterial: 'Titanium',
    caseDiameter: 44,
    strapMaterial: 'Rubber',
    waterResistance: 300,
    color: 'Blue',
    stock: 7,
    isFeatured: false,
    isBestSeller: false,
  },
  {
    name: 'Ball Engineer Hydrocarbon',
    brand: 'Ball',
    price: 3400,
    description: 'Extreme legibility, micro gas tubes, 300m water resistant',
    images: ['https://images.unsplash.com/photo-1523170335258-f5ed11844a49'],
    category: 'Dive',
    movement: 'Automatic',
    caseMaterial: 'Stainless Steel',
    caseDiameter: 42,
    strapMaterial: 'Stainless Steel',
    waterResistance: 300,
    color: 'Black',
    stock: 10,
    isFeatured: false,
    isBestSeller: false,
  },
  {
    name: 'Sinn 556',
    brand: 'Sinn',
    price: 1420,
    description: 'German tool watch, anti-magnetic, scratch-resistant crystal',
    images: ['https://images.unsplash.com/photo-1612817159949-195b6eb9e31a'],
    category: 'Field',
    movement: 'Automatic',
    caseMaterial: 'Stainless Steel',
    caseDiameter: 38,
    strapMaterial: 'Leather',
    waterResistance: 200,
    color: 'Black',
    stock: 16,
    isFeatured: false,
    isBestSeller: true,
  },
  {
    name: 'Frederique Constant Slimline Moonphase',
    brand: 'Frederique Constant',
    price: 1895,
    description: 'Affordable moonphase complication, elegant design',
    images: ['https://images.unsplash.com/photo-1625948515291-69613efd103f'],
    category: 'Dress',
    movement: 'Automatic',
    caseMaterial: 'Stainless Steel',
    caseDiameter: 40,
    strapMaterial: 'Leather',
    waterResistance: 50,
    color: 'White',
    stock: 13,
    isFeatured: false,
    isBestSeller: false,
  },
  {
    name: 'Rado Captain Cook',
    brand: 'Rado',
    price: 2350,
    description: 'Vintage dive watch reissue, bronze case, heritage design',
    images: ['https://images.unsplash.com/photo-1617625802912-cdf23d9a6e18'],
    category: 'Dive',
    movement: 'Automatic',
    caseMaterial: 'Bronze',
    caseDiameter: 42,
    strapMaterial: 'Leather',
    waterResistance: 300,
    color: 'Green',
    stock: 11,
    isFeatured: false,
    isBestSeller: false,
  },
  {
    name: 'Mido Ocean Star',
    brand: 'Mido',
    price: 1150,
    description: 'Gradient dial, 80-hour power reserve, exceptional value',
    images: ['https://images.unsplash.com/photo-1639006570490-79c0c53f1080'],
    category: 'Dive',
    movement: 'Automatic',
    caseMaterial: 'Stainless Steel',
    caseDiameter: 40,
    strapMaterial: 'Stainless Steel',
    waterResistance: 200,
    color: 'Blue',
    stock: 22,
    isFeatured: false,
    isBestSeller: true,
  },
  {
    name: 'Baume & Mercier Clifton Baumatic',
    brand: 'Baume & Mercier',
    price: 3100,
    description: '5-day power reserve, silicon balance spring, COSC certified',
    images: ['https://images.unsplash.com/photo-1607513234392-fab5ed87e611'],
    category: 'Dress',
    movement: 'Automatic',
    caseMaterial: 'Stainless Steel',
    caseDiameter: 40,
    strapMaterial: 'Leather',
    waterResistance: 50,
    color: 'White',
    stock: 9,
    isFeatured: false,
    isBestSeller: false,
  },
  {
    name: 'Certina DS Action Diver',
    brand: 'Certina',
    price: 795,
    description: 'Budget-friendly dive watch, 300m water resistant, ISO 6425 certified',
    images: ['https://images.unsplash.com/photo-1618481187757-5d27c7dc3071'],
    category: 'Dive',
    movement: 'Automatic',
    caseMaterial: 'Stainless Steel',
    caseDiameter: 43,
    strapMaterial: 'Rubber',
    waterResistance: 300,
    color: 'Black',
    stock: 28,
    isFeatured: false,
    isBestSeller: true,
  },
  {
    name: 'Alpina Alpiner 4',
    brand: 'Alpina',
    price: 1295,
    description: 'Swiss sports watch, 100-hour power reserve, outdoor design',
    images: ['https://images.unsplash.com/photo-1614164185816-0e043ea08013'],
    category: 'Field',
    movement: 'Automatic',
    caseMaterial: 'Stainless Steel',
    caseDiameter: 44,
    strapMaterial: 'Leather',
    waterResistance: 100,
    color: 'Black',
    stock: 15,
    isFeatured: false,
    isBestSeller: false,
  },
  {
    name: 'Raymond Weil Freelancer',
    brand: 'Raymond Weil',
    price: 1695,
    description: 'Swiss chronograph, tachymeter bezel, sporty elegance',
    images: ['https://images.unsplash.com/photo-1606390962981-e464eb6c5c39'],
    category: 'Chronograph',
    movement: 'Automatic',
    caseMaterial: 'Stainless Steel',
    caseDiameter: 43,
    strapMaterial: 'Stainless Steel',
    waterResistance: 100,
    color: 'Black',
    stock: 12,
    isFeatured: false,
    isBestSeller: false,
  },
  {
    name: 'Eterna KonTiki Diver',
    brand: 'Eterna',
    price: 2900,
    description: 'Heritage dive watch, spherodrive technology, bronze case',
    images: ['https://images.unsplash.com/photo-1611148458170-9a16d9fdd1f6'],
    category: 'Dive',
    movement: 'Automatic',
    caseMaterial: 'Bronze',
    caseDiameter: 44,
    strapMaterial: 'Rubber',
    waterResistance: 500,
    color: 'Green',
    stock: 8,
    isFeatured: false,
    isBestSeller: false,
  },
  {
    name: 'Carl F. Bucherer Manero Peripheral',
    brand: 'Carl F. Bucherer',
    price: 9800,
    description: 'Peripheral rotor movement, ultra-thin automatic, luxury finishing',
    images: ['https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a'],
    category: 'Dress',
    movement: 'Automatic',
    caseMaterial: 'Rose Gold',
    caseDiameter: 40,
    strapMaterial: 'Leather',
    waterResistance: 30,
    color: 'White',
    stock: 3,
    isFeatured: true,
    isBestSeller: false,
  },
  {
    name: 'Rolex GMT-Master II',
    brand: 'Rolex',
    price: 18700,
    description: 'Dual timezone traveler watch, ceramic bezel, jubilee bracelet',
    images: ['https://images.unsplash.com/photo-1587836374775-5ac0c85d9e57'],
    category: 'GMT',
    movement: 'Automatic',
    caseMaterial: 'Stainless Steel',
    caseDiameter: 40,
    strapMaterial: 'Stainless Steel',
    waterResistance: 100,
    color: 'Black/Blue',
    stock: 2,
    isFeatured: true,
    isBestSeller: true,
  },
  {
    name: 'Omega Constellation',
    brand: 'Omega',
    price: 6800,
    description: 'Elegant dress watch, star emblem, Co-Axial escapement',
    images: ['https://images.unsplash.com/photo-1533139502658-0198f920d8e8'],
    category: 'Dress',
    movement: 'Automatic',
    caseMaterial: 'Stainless Steel',
    caseDiameter: 39,
    strapMaterial: 'Stainless Steel',
    waterResistance: 100,
    color: 'Silver',
    stock: 10,
    isFeatured: false,
    isBestSeller: true,
  },
  {
    name: 'IWC Portugieser Chronograph',
    brand: 'IWC',
    price: 12500,
    description: 'Classic chronograph, leaf-shaped hands, elegant proportions',
    images: ['https://images.unsplash.com/photo-1594534475808-b18fc33b045e'],
    category: 'Chronograph',
    movement: 'Automatic',
    caseMaterial: 'Stainless Steel',
    caseDiameter: 41,
    strapMaterial: 'Leather',
    waterResistance: 30,
    color: 'White',
    stock: 5,
    isFeatured: true,
    isBestSeller: false,
  },
  {
    name: 'Tudor Pelagos FXD',
    brand: 'Tudor',
    price: 4200,
    description: 'Military dive watch, fixed strap bars, titanium case',
    images: ['https://images.unsplash.com/photo-1622434641406-a158123450f9'],
    category: 'Dive',
    movement: 'Automatic',
    caseMaterial: 'Titanium',
    caseDiameter: 42,
    strapMaterial: 'Fabric',
    waterResistance: 200,
    color: 'Black',
    stock: 8,
    isFeatured: false,
    isBestSeller: true,
  },
  {
    name: 'Breitling Superocean Heritage',
    brand: 'Breitling',
    price: 5200,
    description: 'Vintage-inspired dive watch, ceramic bezel, 200m water resistant',
    images: ['https://images.unsplash.com/photo-1614164185128-e4ec99c436d7'],
    category: 'Dive',
    movement: 'Automatic',
    caseMaterial: 'Stainless Steel',
    caseDiameter: 44,
    strapMaterial: 'Stainless Steel',
    waterResistance: 200,
    color: 'Blue',
    stock: 9,
    isFeatured: false,
    isBestSeller: false,
  },
];

export async function seedProducts() {
  console.log('🌱 Starting to seed 50 luxury watch products...\n');
  
  let successCount = 0;
  let errorCount = 0;

  for (let i = 0; i < luxuryWatches.length; i++) {
    const watch = luxuryWatches[i];
    try {
      await productsApi.create(watch);
      successCount++;
      console.log(`✅ [${i + 1}/50] Created: ${watch.brand} ${watch.name}`);
    } catch (error: any) {
      errorCount++;
      console.error(`❌ [${i + 1}/50] Failed: ${watch.brand} ${watch.name}`);
      console.error(`   Error: ${error.message}`);
    }
  }

  console.log(`\n📊 Seed Summary:`);
  console.log(`   ✅ Success: ${successCount}`);
  console.log(`   ❌ Failed: ${errorCount}`);
  console.log(`   📦 Total: ${luxuryWatches.length}`);
}

if (require.main === module) {
  seedProducts()
    .then(() => {
      console.log('\n✨ Seeding completed!');
      process.exit(0);
    })
    .catch((error) => {
      console.error('\n💥 Seeding failed:', error);
      process.exit(1);
    });
}
